### PR TITLE
Store Stern user ID for better visiting

### PR DESCRIPTION
**Pull request by deecewan**
this lets us jump directly to a player instead of having to go through search every time

### CODE REVIEW

**Review by xaviershay — APPROVED** [review]
My first reaction was "this seems more brittle" BUT tbh Stern probably more likely to change their buttons and shit than their nav than their URLs so I think my first reaction was wrong.

**Comment by deecewan** [comment]
tbh i think it's the same amount of brittle but if we're going strictly off the definition of "URL" it should always point at the resource 🤷

**Comment by xaviershay** [comment]
so in summary we don't trust Stern to not have a shit website :(

**Comment by xaviershay** [comment]
... we still want to merge this, right?

**Comment by deecewan** [comment]
🤷 no idea.

**Comment by deecewan** [comment]
seems good 🤷

**Pull request merged**
